import * as cart from "./cart-data";
export declare const store: import("@stencil/store").ObservableMap<{
  api: cart.api;
  totalValue: number;
  productValue: number;
  productAmount: number;
  pointsForOrder: number;
  totalShippingTime: string;
  otherValues: cart.summaryItem[];
  shippingProgress: cart.shippingProgress;
  products: cart.product[];
  deals: cart.deal[];
  dealGroups: cart.dealGroup[];
  shipping: cart.selectItem[];
  payment: cart.selectItem[];
  shippingMessage: string;
  paymentMessage: string;
  activeShipping: number;
  activePayment: number;
  points: cart.points;
  discount: cart.discount;
  loading: number;
  loadingProducts: number;
  loadingDeals: boolean;
  easyprotect: cart.easyprotect;
  insured: cart.easyprotectInsured;
}>;
export declare function easyprotectChange(insured: cart.easyprotectInsured): Promise<void>;
export declare function easyprotectRemove(id: string): Promise<void>;
